# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml
seed: 42

policy: 'MlpPolicy'
n_timesteps: !!float 1e8
batch_size: 512
n_steps: 8
gamma: 0.99
learning_rate: !!float 2.5e-4
ent_coef: 0.0
clip_range: 0.2
n_epochs: 4
gae_lambda: 0.95
max_grad_norm: 1.0
vf_coef: 0.5
device: "cpu"
policy_kwargs: "dict(
                    log_std_init=0,
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[512,512, 256], vf=[512,512, 256]),
                )"

# 归一化参数
# normalize_input: true    # 启用观察归一化
# normalize_value: true    # 启用奖励归一化
