seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    # min_log_std: -0.0  # std = 1.0
    # min_log_std: -0.7  # std = 0.5
    # min_log_std: -1.2  # std = 0.3
    min_log_std: -2.3  # std = 0.1
    # min_log_std: -4.6  # std = 0.01
    max_log_std: 0.26  # std = 1.3
    # initial_log_std: -0.7  # std = 0.5
    # initial_log_std: -1.2  # std = 0.3
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [1024, 512, 256, 128]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [1024, 512, 256, 128]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# MAPPO agent configuration (field names are from MAPPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/multi_agents/mappo.html
agent:
  class: MAPPO
  param_sharing: True
  rollouts: 250
  learning_epochs: 5

  mini_batches: 50
  # mini_batches: 40  # RTX 4090: 12000 envs, 40 mini-batches
  # mini_batches: 50  # RTX 4070 Ti SUPER: 10000 envs, 50 mini-batches
  # mini_batches: 25  # RTX 4080 Laptop: 5000 envs, 25 mini-batches

  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0005
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
    max_lr: 0.0005
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  shared_state_preprocessor: RunningStandardScaler
  shared_state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.001
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: ""
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: 10000


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 500000
  environment_info: log
